# Generated by Django 3.2.12 on 2022-05-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_teachers_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='profile_image',
        ),
    ]
