# Generated by Django 3.2.12 on 2022-05-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_repositories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectstudentrelation',
            name='subject',
        ),
        migrations.AddField(
            model_name='subjectstudentrelation',
            name='repository',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.repositories'),
        ),
    ]
